/*
 * Example API Users
 * API about users management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UserApi
 */
//@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * Get users information
     *
     * Returns a list of users
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listUsersTest() throws Exception {
        api.listUsers();

        // TODO: test validations
    }
}
